comment out part of ensure up to date

diff --git a/bin/utils/ensure-up-to-date b/bin/utils/ensure-up-to-date
--- a/bin/utils/ensure-up-to-date
+++ b/bin/utils/ensure-up-to-date
@@ -28,22 +28,22 @@ fi
 
 # Some special case generators may expect to be run as a stanalone process (e.g. modifying classpath)
 # Docs should always be run, regardless of batch or operation.
-declare -a always_iterate=(
-"${root}/bin/meta-codegen.sh"
-"${root}/bin/utils/export_docs_generators.sh"
-"${root}/bin/utils/copy-to-website.sh"
-"${root}/bin/utils/export_generators_readme.sh"
-)
-
-for i in "${always_iterate[@]}"; do
-    echo "Starting $i ..."
-    if eval "$i"; then
-      echo "Executed $i successfully!"
-    else
-      echo "ERROR: Failed to run $i"
-      exit 1
-    fi
-done
+#declare -a always_iterate=(
+#"${root}/bin/meta-codegen.sh"
+#"${root}/bin/utils/export_docs_generators.sh"
+#"${root}/bin/utils/copy-to-website.sh"
+#"${root}/bin/utils/export_generators_readme.sh"
+#)
+#
+#for i in "${always_iterate[@]}"; do
+#    echo "Starting $i ..."
+#    if eval "$i"; then
+#      echo "Executed $i successfully!"
+#    else
+#      echo "ERROR: Failed to run $i"
+#      exit 1
+#    fi
+#done
 
 # Check:
 if [ -n "$(git status --porcelain)" ]; then
